/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS "Threads" (
	"_id" VARCHAR(24) NOT NULL,
	"title" TEXT NULL DEFAULT NULL,
	"course_id" VARCHAR(50) NULL DEFAULT NULL,
	"username" VARCHAR(50) NULL DEFAULT NULL,
	"comments_count" INTEGER NULL DEFAULT NULL,
	PRIMARY KEY ("_id"),
	CONSTRAINT "thread_fk_course" FOREIGN KEY ("course_id") REFERENCES "course" ("course_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT "threads_fk_user" FOREIGN KEY ("username") REFERENCES "User" ("username") ON UPDATE NO ACTION ON DELETE NO ACTION
);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
